services:
  levelup:
    container_name: levelup_bot
    image: brifboy/levelup
    build: .
    depends_on:
      database:
        condition: service_healthy
    networks:
      - levelup
    environment:
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_URL=jdbc:postgresql://database/levelupdb
      - DISCORD_TOKEN=${DISCORD_TOKEN}


  database:
    container_name: levelup_database
    image: postgres:17.5
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_DB=levelupdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d levelupdb"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - levelup
    ports:
      - "5432:5432"

networks:
  levelup:
    driver: bridge
