
services:
  levelup:
    container_name: levelup_bot
    image: levelup
    build: .
    depends_on:
      database:
        condition: service_healthy
    networks:
      - levelup
    environment:
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_URL=jdbc:postgresql://database/levelupdb
      - DISCORD_TOKEN=${DISCORD_TOKEN}


  database:
    container_name: levelup_database
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USERNAME=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRESQL_DATABASE=levelupdb
    healthcheck:
      test: ["CMD-shell", "pg_isready -U ${DATASOURCE_USERNAME} -d levelupdb"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - levelup
    ports:
      - "5432:5432"

networks:
  levelup:
    driver: bridge

